# 运行端口
port: 9999

# MySQL数据库配置
mysql:
  host: 10.0.5.2
  port: 3306
  database: neko_music
  username: root
  password: wcjs123

# Redis配置
redis:
  host: 10.0.5.2
  port: 6379

# JWT配置
jwt:
  secret: defaultSecretKeyForNekoMusic
  expiration: 86400  # 24小时（秒）

# 邮件服务器
smtp:
  host: smtp.exmail.qq.com
  port: 465
  username: support@cnmsb.xin
  password: qTHWV9pU4fR52rGf
  ssl: true
  tls: false

# 白名单邮箱
blacklist_email:
  - 10minutemail.com
  - mailinator.com
  - temp-mail.org
  - maildrop.cc
  - guerrillamail.com
  - sharklasers.com
  - getnada.com
  - mintemail.com
  - trashmail.com
  - mailnesia.com
  - dispostable.com
  - tempmailaddress.com
  - mytemp.email
  - emailondeck.com
  - throwawaymail.com
  - spoofmail.de
  - fakeinbox.com
  - instantemailaddress.com
  - spamgourmet.com
  - getairmail.com
  - tempail.com
  - spam4.me
  - 33mail.com
  - moakt.com
  - mailsac.com
  - mailnull.com
  - tempmailo.com
  - dropmail.me
  - owlymail.com
  - fakemail.net
  - luxusmail.org
  - edumail.icu
  - emailtemporal.org
  - spambox.us
  - tempemail.co
  - mail7.io
  - temp-mail.io
  - tmail.ai
  - notmailinator.com
  - anonaddy.com
  - emailsensei.com
  - burnermail.io
  - dismail.de
  - guerrillamail.net
  - mailcatch.com
  - nada.ltd
  - mail-tester.com
  - fakebox.org
  - tempinbox.com
  - gettempmail.com
  - mailpoof.com
  - yopmail.com
  - iwatermail.com
  - tankmail.cn
  - skymail.ink
  - 022335.xyz
  - snd.de5.net
  - mohmal.com
  - mytrashmailer.com
  - tempmail.plus
  - throwawaymail.io
  - spamcero.com
  - fakemailgenerator.com
  - tempmail.ninja
  - tempmailgen.com
  - mailcatcher.net
  - trashmail.io
  - spambog.com
  - spambog.de
  - spambog.ru
  - mailtwt.com
  - tmpmail.net
  - emailfake.com
  - emailfake.org
  - shortmail.xyz
  - tempmail.net
  - tempcloud.info
  - tempomail.fr
  - trashmail.se
  - fastmailforyou.xyz
  - mailhub24.com
  - tempmail.sbs
  - tempmail.dev
  - mailbox52.ga
  - tempmails.io
  - instantemail.com
  - throwam.com
  - oneoffmail.com
  - mailtome.de
  - pokemail.net
  - 1secmail.com
  - 1secmail.net
  - 1secmail.org
  - vmail.me
  - fakeinbox.info
  - tempr.email
  - temporarymail.com
  - temporarymail.org
  - my10minutemail.com
  - tempmail.top
  - tempmail.tech
  - trashmail.de
  - tempmail.ws
  - fakermail.com
  - inboxkitten.com
  - simplelogin.co
  - spamstack.net
  - spamavert.com
  - easytrashmail.com
  - spamex.com
  - e4ward.com
  - bmwz.cn
  - fake-mail.cc
  - gettempmail.xyz
  - mail-temporaire.fr
  - tempemail.biz
  - tempemail.io
  - tempemail.org
  - tempinbox.xyz
  - tempomail.io
  - yopmail.fr
  - yopmail.net
  - yopmail.org
  - mailnesia.xyz
  - tempmail.us
  - tempmail.pro
  - fakeemailgenerator.com
  - tempmailer.com
  - mail-temp.com
  - 24hourmail.com
  - emltmp.com
  - spamfree24.org
  - spamfree24.net
  - spamfree24.com
  - nowmymail.com
  - mailbox92.com
  - yspmail.com
  - zippymail.info
  - mailhazard.com
  - freetempemail.com
  - tempmailid.com
  - fakeemails.us
  - tempmailname.com
  - easy-mail.org
  - fakeemail.net
  - anyalias.com
  - mailwoo.com
  - trashbox.io
  - cloudmail.life
  - mailtemp.info
  - mytrashmail.com
  - mytempmail.com
  - temp-mail.dev
  - tempmail.pw
  - tempmail.bid
  - tempmail.buzz
  - mailbox.in.ua
  - tempmail.host
  - tempmail.us.to
  - tempmail.bid
  - spamthisplease.com
  - disposable-mail.com
  - disposableemail.org
  - trashmail.fr
  - throwaway.io
  - trashmail.live
  - tempmail.lol
  - tempmail.cyou
  - tempmail.kim
  - tempmail.run
  - fakeinbox.co
  - opencraftgames.com
  - fakeinbox.cc
  - fakemail.me
  - trashmail.world
  - mailrocks.net
  - mytempmail.co
  - tempmail.space
  - mailtemp.org
  - tempmail.art
  - temp-mail.us
  - get-mail.xyz
  - mail.boo
  - emailtemp.org
  - tempmail.ms
  - spammail.me
  - xeocustom.com