# 运行端口
port: 9999

# MySQL数据库配置
mysql:
  host: 127.0.0.1
  port: 3306
  database: neko_music
  username: root
  password: wcjs123

# Redis配置
redis:
  host: 127.0.0.1
  port: 6379

# Hook消息配置
# astrbot 插件 https://github.com/MinecraftNekoServer/astrbot_msg_hook
Msg:
  url: 127.0.0.1:8080
  token: Fantasy_Network

# JWT配置
jwt:
  secret: defaultSecretKeyForNekoMusic
  expiration: 86400  # 24小时（秒）

# 邮件服务器
smtp:
  host: smtp.exmail.qq.com
  port: 465
  username: support@cnmsb.xin
  password: qTHWV9pU4fR52rGf
  ssl: true
  tls: false

# 白名单邮箱
whitelist_email:
  - qq.com
  - gmail.com
